version: '3.5'
services:
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - '3000:80'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '58642:58642'
    volumes:
      - type: bind
        source: ~/db/db.db
        target: /db.db
      - type: bind
        source: ~/db/cert.pem
        target: /cert.pem
      - type: bind
        source: ~/db/privkey.pem
        target: /privkey.pem

networks:
  default:
    name: table_tennis_network
