version: '3.5'
services:
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    ports:
      - '3000:80'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '58642:58642'
    volumes:
      - type: bind
        source: ./server/src/db.db
        target: /db.db

networks:
  default:
    name: table_tennis_network
