version: '3.5'
services:
  website:
    build:
      context: ./website
      dockerfile: Dockerfile
      args:
        build_mode: 'build:prod'
    ports:
      - '3000:3000'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '58642:58642'
    volumes:
      - type: bind
        source: ~/db/db.db
        target: /db.db
      - type: bind
        source: ~/db
        target: /db
  website-dev:
    build:
      context: ./website
      dockerfile: Dockerfile
      args:
        build_mode: 'build:dev'
    ports:
      - '5000:3000'
  server-dev:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        build_mode: '--debug'
    ports:
      - '38642:58642'
    volumes:
      - type: bind
        source: ~/db-development/db.db
        target: /db.db
      - type: bind
        source: ~/db-development
        target: /db

networks:
  default:
    name: table_tennis_network
