name: Docker Image CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
        with: 
          clean: false
      - name: Build the stack
        run: docker-compose build --parallel
      - name: Bring up
        run: docker-compose up -d
