name: Rust

on:
  pull_request:
    branches: [ development ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
       cd server/src
       cargo test
